// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccounts = `-- name: CreateAccounts :execresult
INSERT INTO accounts (
  owner,balance,currency
) VALUES (
  ?, ?, ?
)
`

type CreateAccountsParams struct {
	Owner    string `json:"owner"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccounts(ctx context.Context, arg CreateAccountsParams) (sql.Result, error) {
	return q.exec(ctx, q.createAccountsStmt, createAccounts, arg.Owner, arg.Balance, arg.Currency)
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteAccountStmt, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id,owner,balance,currency,created_at FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIDStmt, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByIDForUpdate = `-- name: GetAccountByIDForUpdate :one
SELECT id,owner,balance,currency,created_at FROM accounts
WHERE id = ?
FOR UPDATE
`

func (q *Queries) GetAccountByIDForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIDForUpdateStmt, getAccountByIDForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getLastAccount = `-- name: GetLastAccount :one
SELECT id,owner,balance,currency,created_at FROM accounts
ORDER BY id DESC 
LIMIT 1
`

func (q *Queries) GetLastAccount(ctx context.Context) (Account, error) {
	row := q.queryRow(ctx, q.getLastAccountStmt, getLastAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id,owner,balance,currency,created_at FROM accounts
ORDER BY id
LIMIT ? 
OFFSET ?
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.query(ctx, q.listAccountsStmt, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :execresult
UPDATE accounts 
SET owner = ?,balance = ?,currency = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	Owner    string `json:"owner"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (sql.Result, error) {
	return q.exec(ctx, q.updateAccountStmt, updateAccount,
		arg.Owner,
		arg.Balance,
		arg.Currency,
		arg.ID,
	)
}
